doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            UserId: App\Infrastructure\Persistence\Doctrine\UserManagement\User\DoctrineUserId
            Email: App\Infrastructure\Persistence\Doctrine\UserManagement\User\DoctrineEmail
            Password: App\Infrastructure\Persistence\Doctrine\UserManagement\User\DoctrinePassword
            QuestionId: App\Infrastructure\Persistence\Doctrine\QuestionManagement\Question\DoctrineQuestionId


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: App
