version: "3.1"

services:
  php:
    image: fsilva/php:7.4
    volumes:
    - ./:/var/www/app
    ports:
    - 8080:80
    environment:
      USE_XDEBUG: "yes"
      USE_OPCACHE: "yes"
      WEBROOT: public

  database:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=secret
