version: "3.1"

services:
  php:
    image: fsilva/php:7.4
    volumes:
    - ./:/var/www/app
    ports:
    - 80
    environment:
      USE_XDEBUG: "yes"
      USE_OPCACHE: "yes"
      WEBROOT: public